FROM python:3.11.11

WORKDIR /app


# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the files
COPY . .


# Run the application
CMD ["python", "rss_script.py"]
